### ISSUE TITLE
Post-it contents not preserving through toggles

### ISSUE THREAD

**Issue by Snaid1** [Snaid1/BHUD-Blishpad#46]
From Github User Voidrazer:

"I'm not sure if it's intended to, but the Preserve Post-It Contents option does not preserve the contents between toggles. Noting something down and toggling it away to clear screen real estate seems like normal operating procedure but upon toggling the post-it back, the contents are reset"

**Comment by Snaid1** [comment]
originally posted to the BHUD pkgs repo.
https://github.com/blish-hud/bhud-pkgs/issues/162

**Comment by Snaid1** [comment]
@Voidraizer this bugfix is in Blishpad v1.1.3 which is now released and available for download in BlishHUD

**Comment by Voidraizer** [comment]
Thank you!!
